In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('dataset.csv')
df.head()
sum(df['Unusual'])

10183

In [ ]:

df.drop(['maxUE_UL+DL','Time','CellName'], axis=1,inplace=True)
df.head()

PRBUsageUL  PRBUsageDL  meanThr_DL  meanThr_UL  maxThr_DL  maxThr_UL  \
0      11.642       1.393       0.370       0.041     15.655      0.644   
1      21.791       1.891       0.537       0.268     10.273      1.154   
2       0.498       0.398       0.015       0.010      0.262      0.164   
3       1.891       1.095       0.940       0.024     60.715      0.825   
4       0.303       0.404       0.016       0.013      0.348      0.168   

   meanUE_DL  meanUE_UL  maxUE_DL  maxUE_UL  Unusual  
0      1.114      1.025       4.0       3.0        1  
1      1.353      1.085       6.0       4.0        1  
2      0.995      0.995       1.0       1.0        1  
3      1.035      0.995       2.0       2.0        1  
4      1.011      1.011       2.0       1.0        0

In [ ]:
print('number of missing values')
for col in df.columns:
    if col not in ['Time','CellName']:
        print(col,df[col].isnull().sum())
        df[col]=pd.to_numeric(df[col], errors='coerce')
df['maxUE_DL'].fillna(value=df['maxUE_DL'].mean(), inplace=True)
df['maxUE_UL'].fillna(value=df['maxUE_UL'].mean(), inplace=True)

In [ ]:
print('number of missing values')
for col in df.columns:
    if col not in ['Time','CellName']:
        print(col,df[col].isnull().sum())

number of missing values
PRBUsageUL 0
PRBUsageDL 0
meanThr_DL 0
meanThr_UL 0
maxThr_DL 0
maxThr_UL 0
meanUE_DL 0
meanUE_UL 0
maxUE_DL 0
maxUE_UL 0
Unusual 0


In [ ]:
# for col in df.columns:
#     mean=df[col].mean()
#     Q1 = np.percentile(df[col], 25,method = 'midpoint')
 
#     Q3 = np.percentile(df[col], 75,method = 'midpoint')
#     IQR = Q3 - Q1
    
#     upper =  Q3+1.5*IQR
#     lower = Q1-1.5*IQR
#     df.loc[df[col] > upper, col] = mean
#     df.loc[df[col] > lower, col] = mean
interval = 3
sample4 = df.iloc[::interval]
sample4['Class'].value_counts() 


In [ ]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]

In [ ]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(sampling_strategy='minority')
X_sm, y_sm = smote.fit_resample(X, Y)

y_sm.value_counts()

1    26721
0    26721
Name: Unusual, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X_sm, y_sm, test_size = 0.25, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)


Logistic Regression

In [ ]:

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)


y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[3292 3470]
 [1633 4966]]


c:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.6180675099169224

K Nearest Neighbours

In [ ]:

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)


y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[4715 2047]
 [1190 5409]]


0.7577277149913929

Support Vector Machine

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[4599 2163]
 [1538 5061]]


0.7229997754659082

Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)


y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2327 4435]
 [1206 5393]]


0.577801062794701

Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)


y_pred = classifier.predict(X_test)


from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[6535  227]
 [ 237 6362]]


0.9652720604745154

Random Forest 

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)


y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[6618  144]
 [ 559 6040]]


0.9473841778310007

Artifcial Neural Network

In [ ]:
import tensorflow as tf
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Part 3 - Training the ANN

# Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
1253/1253 [==============================] - 3s 2ms/step - loss: 0.6736 - accuracy: 0.5771
Epoch 2/100
1253/1253 [==============================] - 2s 2ms/step - loss: 0.6557 - accuracy: 0.6075
Epoch 3/100
1253/1253 [==============================] - 2s 2ms/step - loss: 0.6504 - accuracy: 0.6149
Epoch 4/100
1253/1253 [==============================] - 2s 2ms/step - loss: 0.6451 - accuracy: 0.6249
Epoch 5/100
1253/1253 [==============================] - 2s 2ms/step - loss: 0.6364 - accuracy: 0.6369
Epoch 6/100
1253/1253 [==============================] - 2s 2ms/step - loss: 0.6225 - accuracy: 0.6612
Epoch 7/100
1253/1253 [==============================] - 2s 2ms/step - loss: 0.6101 - accuracy: 0.6773
Epoch 8/100
1253/1253 [==============================] - 2s 2ms/step - loss: 0.5993 - accuracy: 0.6840
Epoch 9/100
1253/1253 [==============================] - 2s 2ms/step - loss: 0.5900 - accuracy: 0.6942
Epoch 10/100
1253/1253 [==============================] - 2s 2ms/step - l

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

418/418 [==============================] - 1s 1ms/step
[[5212 1550]
 [2003 4596]]


0.7340767906593818